[project]
name = "jcpao-court-directory"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cloudinary>=1.44.1",
    "psycopg[binary,pool]>=3.2.12",
    "streamlit>=1.51.0",
]
